### ISSUE TITLE
async component

### ISSUE THREAD

**Issue by 5chao** [mozilla-neutrino/react-router-starter#10]
when async component, the import css file in component can not be async load

**Comment by helfi92** [comment]
Right now the css file `App.css` is loaded at start. If you want to load this file asynchronously then  simply place the `import` statement inside an asynchronous route.

_Example: Import `App.css` when accessing /foo_
```javascript
// src/components/Foo/Foo.js
import React from 'react';
import '../../App.css';

const Foo = () => <h1>Foo</h1>;

export default Foo;
```

**Comment by helfi92** [comment]
Closing this issue. Feel free to reopen if your problem is still not resolved.
