### ISSUE TITLE
Hot reload doesn't work

### ISSUE THREAD

**Issue by cuongngosa** [mozilla-neutrino/react-router-starter#4]
I just simple test change text Home to Homepage.
in console show
Source changed, re-compilling
Build completed
But in browser doesn't see change affect
Do u have any idea ?

**Comment by cuongngosa** [comment]
Hang at App updated. Recompiling...

**Comment by cuongngosa** [comment]
I tried press save file second time then hot reload works. I have no idea.

**Comment by helfi92** [comment]
@cuongngosa It's a current issue with Neutrino where the first save hangs but subsequent saves work as intended.
