### ISSUE TITLE
HMR is not  working

### ISSUE THREAD

**Issue by kishorevarma** [mozilla-neutrino/react-router-starter#5]
Hi,

I have cloned your project and tried, it seems HMR is not working.is it only for me.

Thanks
Kishorevarma

**Comment by helfi92** [comment]
@kishorevarma, HMR doesn't seem to work on the first save but subsequent saves should work.

**Comment by kishorevarma** [comment]
HMR works only for home page, its not working for async modules(Foo.js, Bar.js). go to foo page and change the text there

**Comment by helfi92** [comment]
You're right. I have a feeling hot reloading stopped working after introducing asynchronous loading of components. I'll inspect!

**Comment by helfi92** [comment]
@kishorevarma I updated the repo to neutrino v6 and made HMR work. Enjoy!

**Comment by kishorevarma** [comment]
thank you @helfi92
